# AndroidX — obligatoire pour tout projet moderne
android.useAndroidX=true

# Kotlin Incremental + Daemon
kotlin.incremental=true
kotlin.daemon.jvm.options=-Xmx2g

# Gradle JVM heap
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Parallélisation et cache Gradle
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Désactive la collecte de données Android
android.enableJetifier=false
